package util;

import java.util.List;

public enum UnicodeDrawing {


    // BOX DRAWING 

    LIGHT_HORIZONTAL('─'),
    HEAVY_HORIZONTAL('━'),
    LIGHT_VERTICAL('│'),
    HEAVY_VERTICAL('┃'),

    LIGHT_TRIPE_DASH_HORIZONTAL('┄'),
    HEAVY_TRIPE_DASH_HORIZONTAL('┅'),
    LIGHT_TRIPE_DASH_VERTICAL('┆'),
    HEAVY_TRIPE_DASH_VERTICAL('┇'),

    LIGHT_QUADRUPLE_DASH_HORIZONTAL('┈'),
    HEAVY_QUADRUPLE_DASH_HORIZONTAL('┉'),
    LIGHT_QUADRUPLE_DASH_VERTICAL('┊'),
    HEAVY_QUADRUPLE_DASH_VERTICAL('┋'),

    LIGHT_DOWN_AND_RIGHT('┌'),
    DOWN_LIGHT_AND_RIGHT_HEAVY('┍'),
    DOWN_HEAVY_AND_RIGHT_LIGHT('┎'),
    HEAVY_DOWN_AND_RIGHT('┏'),

    LIGHT_DOWN_AND_LEFT('┐'),
    DOWN_LIGHT_AND_LEFT_HEAVY('┑'),
    DOWN_HEAVY_AND_LEFT_LIGHT('┒'),
    HEAVY_DOWN_AND_LEFT('┓'),

    LIGHT_UP_AND_RIGHT('└'),
    UP_LIGHT_AND_RIGHT_HEAVY('┕'),
    UP_HEAVY_AND_RIGHT_LIGHT('┖'),
    HEAVY_UP_AND_RIGHT('┗'),

    LIGHT_UP_AND_LEFT('┘'),
    UP_LIGHT_AND_LEFT_HEAVY('┙'),
    UP_HEAVY_AND_LEFT_LIGHT('┚'),
    HEAVY_UP_AND_LEFT('┛'),

    LIGHT_VERTICAL_AND_RIGHT('├'),
    VERTICAL_LIGHT_AND_RIGHT_HEAVY('┝'),
    UP_HEAVY_AND_RIGHT_DOWN_LIGHT('┞'),
    DOWN_HEAVY_AND_RIGHT_UP_LIGHT('┟'),
    VERTICAL_HEAVY_AND_RIGHT_LIGHT('┠'),
    DOWN_LIGHT_AND_RIGHT_UP_HEAVY('┡'),
    UP_LIGHT_AND_RIGHT_DOWN_HEAVY('┢'),
    HEAVY_VERTICAL_AND_RIGHT('┣'),

    LIGHT_VERTICAL_AND_LEFT('┤'),
    VERTICAL_LIGHT_AND_LEFT_HEAVY('┥'),
    UP_HEAVY_AND_LEFT_DOWN_LIGHT('┦'),
    DOWN_HEAVY_AND_LEFT_UP_LIGHT('┧'),
    VERTICAL_HEAVY_AND_LEFT_LIGHT('┨'),
    DOWN_LIGHT_AND_LEFT_UP_HEAVY('┩'),
    UP_LIGHT_AND_LEFT_DOWN_HEAVY('┪'),
    HEAVY_VERTICAL_AND_LEFT('┫'),

    LIGHT_DOWN_AND_HORIZONTAL('┬'),
    LEFT_HEAVY_AND_RIGHT_DOWN_LIGHT('┭'),
    RIGHT_HEAVY_AND_LEFT_DOWN_LIGHT('┮'),
    DOWN_LIGHT_AND_HORIZONTAL_HEAVY('┯'),
    DOWN_HEAVY_AND_HORIZONTAL_LIGHT('┰'),
    RIGHT_LIGHT_AND_LEFT_DOWN_HEAVY('┱'),
    LEFT_LIGHT_AND_RIGHT_DOWN_HEAVY('┲'),
    HEAVY_DOWN_AND_HORIZONTAL('┳'),

    LIGHT_UP_AND_HORIZONTAL('┴'),
    LEFT_HEAVY_AND_RIGHT_UP_LIGHT('┵'),
    RIGHT_HEAVY_AND_LEFT_UP_LIGHT('┶'),
    UP_LIGHT_AND_HORIZONTAL_HEAVY('┷'),
    UP_HEAVY_AND_HORIZONTAL_LIGHT('┸'),
    RIGHT_LIGHT_AND_LEFT_UP_HEAVY('┹'),
    LEFT_LIGHT_AND_RIGHT_UP_HEAVY('┺'),
    HEAVY_UP_AND_HORIZONTAL('┻'),

    LIGHT_VERTICAL_AND_HORIZONTAL('┼'),
    LEFT_HEAVY_AND_RIGHT_VERTICAL_LIGHT('┽'),
    RIGHT_HEAVY_AND_LEFT_VERTICAL_LIGHT('┾'),
    VERTICAL_LIGHT_AND_HORIZONTAL_HEAVY('┿'),
    UP_HEAVY_AND_DOWN_HORIZONTAL_LIGHT('╀'),
    DOWN_HEAVY_AND_UP_HORIZONTAL_LIGHT('╁'),
    VERTICAL_HEAVY_AND_HORIZONTAL_LIGHT('╂'),
    LEFT_UP_HEAVY_AND_RIGHT_DOWN_LIGHT('╃'),
    RIGHT_UP_HEAVY_AND_LEFT_DOWN_LIGHT('╄'),
    LEFT_DOWN_HEAVY_AND_RIGHT_UP_LIGHT('╅'),
    RIGHT_DOWN_HEAVY_AND_LEFT_UP_LIGHT('╆'),
    DOWN_LIGHT_AND_UP_HORIZONTAL_HEAVY('╇'),
    UP_LIGHT_AND_DOWN_HORIZONTAL_HEAVY('╈'),
    RIGHT_LIGHT_AND_LEFT_VERTICAL_HEAVY('╉'),
    LEFT_LIGHT_AND_RIGHT_VERTICAL_HEAVY('╊'),
    HEAVY_VERTICAL_AND_HORIZONTAL('╋'),

    LIGHT_DOUBLE_DASH_HORIZONTAL('╌'),
    HEAVY_DOUBLE_DASH_HORIZONTAL('╍'),
    LIGHT_DOUBLE_DASH_VERTICAL('╎'),
    HEAVY_DOUBLE_DASH_VERTICAL('╏'),

    DOUBLE_HORIZONTAL('═'),
    DOUBLE_VERTICAL('║'),

    DOWN_SINGLE_AND_RIGHT_DOUBLE('╒'),
    DOWN_DOUBLE_AND_RIGHT_SINGLE('╓'),
    DOUBLE_DOWN_AND_RIGHT('╔'),

    DOWN_SINGLE_AND_LEFT_DOUBLE('╕'),
    DOWN_DOUBLE_AND_LEFT_SINGLE('╖'),
    DOUBLE_DOWN_AND_LEFT('╗'),

    UP_SINGLE_AND_RIGHT_DOUBLE('╘'),
    UP_DOUBLE_AND_RIGHT_SINGLE('╙'),
    DOUBLE_UP_AND_RIGHT('╚'),

    UP_SINGLE_AND_LEFT_DOUBLE('╛'),
    UP_DOUBLE_AND_LEFT_SINGLE('╜'),
    DOUBLE_UP_AND_LEFT('╝'),

    VERTICAL_SINGLE_AND_RIGHT_DOUBLE('╞'),
    VERTICAL_DOUBLE_AND_RIGHT_SINGLE('╟'),
    DOUBLE_VERTICAL_AND_RIGHT('╠'),

    VERTICAL_SINGLE_AND_LEFT_DOUBLE('╡'),
    VERTICAL_DOUBLE_AND_LEFT_SINGLE('╢'),
    DOUBLE_VERTICAL_AND_LEFT('╣'),

    DOWN_SINGLE_AND_HORIZONTAL_DOUBLE('╤'),
    DOWN_DOUBLE_AND_HORIZONTAL_SINGLE('╥'),
    DOUBLE_DOWN_AND_HORIZONTAL('╦'),

    UP_SINGLE_AND_HORIZONTAL_DOUBLE('╧'),
    UP_DOUBLE_AND_HORIZONTAL_SINGLE('╨'),
    DOUBLE_UP_AND_HORIZONTAL('╩'),

    VERTICAL_SINGLE_AND_HORIZONTAL_DOUBLE('╪'),
    VERTICAL_DOUBLE_AND_HORIZONTAL_SINGLE('╫'),
    DOUBLE_VERTICAL_AND_HORIZONTAL('╬'),

    LIGHT_ARC_DOWN_AND_RIGHT('╭'),
    LIGHT_ARC_DOWN_AND_LEFT('╮'),
    LIGHT_ARC_UP_AND_LEFT('╯'),
    LIGHT_ARC_UP_AND_RIGHT('╰'),
    LIGHT_DIAGONAL_UPPER_RIGHT_TO_LOWER_LEFT('╱'),
    LIGHT_DIAGONAL_UPPER_LEFT_TO_LOWER_RIGHT('╲'),
    LIGHT_DIAGONAL_CROSS('╳'),

    LIGHT_LEFT('╴'),
    LIGHT_UP('╵'),
    LIGHT_RIGHT('╶'),
    LIGHT_DOWN('╷'),

    HEAVY_LEFT('╸'),
    HEAVY_UP('╹'),
    HEAVY_RIGHT('╺'),
    HEAVY_DOWN('╻'),

    LIGHT_LEFT_AND_HEAVY_RIGHT('╼'),
    LIGHT_UP_AND_HEAVY_DOWN('╽'),
    HEAVY_LEFT_AND_LIGHT_RIGHT('╾'),
    HEAVY_UP_AND_LIGHT_DOWN('╿'),


    // BLOCK ELEMENTS
    UPPER_HALF_BLOCK('▀'),
    LOWER_ONE_EIGHTH_BLOCK('▁'),
    LOWER_ONE_QUARTER_BLOCK('▂'),
    LOWER_THREE_EIGHTHS_BLOCK('▃'),
    LOWER_HALF_BLOCK('▄'),
    LOWER_FIVE_EIGHTHS_BLOCK('▅'),
    LOWER_THREE_QUARTERS_BLOCK('▆'),
    LOWER_SEVEN_EIGHTHS_BLOCK('▇'),
    FULL_BLOCK('█'),
    LEFT_SEVEN_EIGHTHS_BLOCK('▉'),
    LEFT_THREE_QUARTERS_BLOCK('▊'),
    LEFT_FIVE_EIGHTHS_BLOCK('▋'),
    LEFT_HALF_BLOCK('▌'),
    LEFT_THREE_EIGHTHS_BLOCK('▍'),
    LEFT_ONE_QUARTER_BLOCK('▎'),
    LEFT_ONE_EIGHTH_BLOCK('▏'),
    RIGHT_HALF_BLOCK('▐'),
    LIGHT_SHADE('░'),
    MEDIUM_SHADE('▒'),
    DARK_SHADE('▓'),
    UPPER_ONE_EIGHTH_BLOCK('▔'),
    RIGHT_ONE_EIGHTH_BLOCK('▕'),
    QUADRANT_LOWER_LEFT('▖'),
    QUADRANT_LOWER_RIGHT('▗'),
    QUADRANT_UPPER_LEFT('▘'),
    QUADRANT_UPPER_LEFT_AND_LOWER_LEFT_AND_LOWER_RIGHT('▙'),
    QUADRANT_UPPER_LEFT_AND_LOWER_RIGHT('▚'),
    QUADRANT_UPPER_LEFT_AND_UPPER_RIGHT_AND_LOWER_LEFT('▛'),
    QUADRANT_UPPER_LEFT_AND_UPPER_RIGHT_AND_LOWER_RIGHT('▜'),
    QUADRANT_UPPER_RIGHT('▝'),
    QUADRANT_UPPER_RIGHT_AND_LOWER_LEFT('▞'),
    QUADRANT_UPPER_RIGHT_AND_LOWER_LEFT_AND_LOWER_RIGHT('▟'),


    // OTHER

    WHITE_SQUARE('□'),
    BLACK_SQUARE('■'),
    WHITE_SQUARE_ROUNDED('▢'),

    LEFT_ARROW('←'),
    RIGHT_ARROW('→'),
    UP_ARROW('↑'),
    DOWN_ARROW('↓'),

    LEFT_RIGHT_ARROW('↔'),
    UP_DOWN_ARROW('↕'),

    TOP_LEFT_ARROW('↖'),
    TOP_RIGHT_ARROW('↗'),
    BOTTOM_LEFT_ARROW('↙'),
    BOTTOM_RIGHT_ARROW('↘'),

    ENTER_ARROW('↵'),
    ENTER_ARROW_RIGHT('↳'),
    ENTER('⏎'),

    DELETE_RIGHT('⌦'),
    DELETE_LEFT('⌫'),

    COMMAND('⌘'),

    WATCH('⌚'),
    HOURGLASS('⌛'),

    CONTROL_KEY('⎈'),

    EJECT('⏏'),
    SKIP_FORWARD('⏭'),
    FAST_FORWARD('⏩'),
    REWIND('⏪'),
    SKIP_BACKWARD('⏮'),
    PLAY_PAUSE('⏯'),

    SLOW_REWIND('⏴'),
    SLOW_FORWARD('⏵'),
    UP_TRIANGLE('⏶'),
    DOWN_TRIANGLE('⏷'),

    PLAY('⏵'),
    PAUSE('⏸'),
    STOP('⏹'),
    RECORD('⏺'),

    POWER('⏻'),
    SLEEP('⏼'),

    STAR_PIC('⭐'),
    STAR('⭑'),
    STAR_STAMP('⍟'),
    ESCAPE_SYMBOL('⎋'),

    MOON('⏾'),

    ALARM_CLOCK('⏰'),
    STOPWATCH('⏱'),
    TIMER_CLOCK('⏲'),
    
    BRACKET_LEFT('〈'),
    BRACKET_RIGHT('〉'),

    WHITE_CIRCLE('○'),
    BLACK_CIRCLE('●'),
    BLACK_DIAMOND('◆'),
    WHITE_DIAMOND('◇'),
    WHITE_MEDIUM_SQUARE('◻'),
    BLACK_MEDIUM_SQUARE('◼'),
    WHITE_MEDIUM_SMALL_SQUARE('◽'),
    BLACK_MEDIUM_SMALL_SQUARE('◾'),


    FISH_EYE('◉'),

    CIRCLE_WITH_LEFT_HALF_BLACK('◐'),
    CIRCLE_WITH_RIGHT_HALF_BLACK('◑'),
    CIRCLE_WITH_LOWER_HALF_BLACK('◒'),
    CIRCLE_WITH_UPPER_HALF_BLACK('◓'),
    CIRCLE_WITH_UPPER_RIGHT_QUADRANT_BLACK('◔'),
    CIRCLE_WITH_ALL_BUT_UPPER_LEFT_QUADRANT_BLACK('◕'),

    BLACK_LOWER_RIGHT_TRIANGLE('◢'),
    BLACK_LOWER_LEFT_TRIANGLE('◣'),
    BLACK_UPPER_LEFT_TRIANGLE('◤'),
    BLACK_UPPER_RIGHT_TRIANGLE('◥'),

    MANICULE_LEFT_DARK('☚'),
    MANICULE_RIGHT_DARK('☛'),
    MANICULE_LEFT_LIGHT('☜'),
    MANICULE_RIGHT_LIGHT('☞'),
    MANICULE_UP_LIGHT('☝'),
    MANICULE_DOWN_LIGHT('☟'),

    SKULL_AND_CROSSBONES('☠'),

    RADIO_ACTIVE('☢'),
    BIOHAZARD('☣'),
    WARNING('⚠'),
    CADUCEUS('☤'),
    CRESCENT_STAR('☪'),
    PEACE('☮'),
    YIN_YANG('☯'),
    FROWN('☹'),
    SMILE('☺'),
    HEART('♥'),

    MALE('♂'),
    FEMALE('♀'),

    WHITE_KING('♔'),
    WHITE_QUEEN('♕'),
    WHITE_ROOK('♖'),
    WHITE_BISHOP('♗'),
    WHITE_KNIGHT('♘'),
    WHITE_PAWN('♙'),
    BLACK_KING('♚'),
    BLACK_QUEEN('♛'),
    BLACK_ROOK('♜'),
    BLACK_BISHOP('♝'),
    BLACK_KNIGHT('♞'),
    BLACK_PAWN('♟'),

    SPADES('♠'),
    SPADES_LIGHT('♤'),
    HEARTS('♥'),
    HEARTS_LIGHT('♡'),
    DIAMONDS('♦'),
    DIAMONDS_LIGHT('♢'),
    CLUBS('♣'),
    CLUBS_LIGHT('♧'),

    QUARTER_NOTE('♩'),
    EIGHTH_NOTE('♪'),
    BEAMED_EIGHTH_NOTES('♫'),
    BEAMED_SIXTEENTH_NOTES('♬'),
    FLAT('♭'),
    NATURAL('♮'),
    SHARP('♯'),

    RECYCLE('♲'),
    RECYCLE_1('♳'),
    RECYCLE_2('♴'),
    RECYCLE_3('♵'),
    RECYCLE_4('♶'),
    RECYCLE_5('♷'),
    RECYCLE_6('♸'),
    RECYCLE_7('♹'),
    RECYCLE_TRIANGLUR('♺'),
    RECYCLE_DARK('♻'),

    DICE_1('⚀'),
    DICE_2('⚁'),
    DICE_3('⚂'),
    DICE_4('⚃'),
    DICE_5('⚄'),
    DICE_6('⚅'),

    SNOWFLAKE('❄'),
    SNOWMAN('☃'),

    SUN('☀'),
    CLOUD('☁'),
    RAIN('⛆'),
    SNOW_CLOUD('⛈'),
    UMBRELLA('☂'),

    TRUCK('⛟'),
    BOAT('⛴'),
    ANCHOR('⚓'),
    MOUNTAIN('⛰'),
    SKI('⛷'),
    SKATE('⛸'),
    TORII('⛩'),

    CHAIN('⛓'),
    GEAR('⚙'),
    HAMMER('⚒'),
    PICK('⛏'),
    HAMMER_PICK('⚒'),
    
    SHIELD('⛨'),
    SWORD('⚔'),
    FLAG('⚑'),
    CASTLE('⛫'),

    CERES('⚳'),
    PALLAS('⚴'),
    JUNO('⚵'),
    VESTA('⚶'),
    CHIRON('⚷'),
    
    ;


    public char value;
    private UnicodeDrawing(char value) {
        this.value = value;
    }
    
    // ˹ 
    // public List<String> specialChars = List.of(
    //     "─",
    //     "━",
    //     "│",
    //     "┌",
    //     "└",
    //     "┘",
    //     "└",
    //     "├"
    // );
}
